### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-fsgrammar#105]
By @seanpoulter in 
https://github.com/ionide/ionide-vscode-fsharp/issues/923#issuecomment-429334036

---

Would you like me to create a new issue for a different issue with syntax highlighting @MangelMaxime?

![image](https://user-images.githubusercontent.com/2585460/46873552-e0b5c500-ce04-11e8-85cd-2ab7f2980d9e.png)

**Comment by seanpoulter** [comment]
Here's the original snippet:
```
let parseJsonValueArray (str: string) (mapping: (JsonValue -> 'a)): ('a list) =
    str
```

It looks like the problem is the space after the type wrapped in `()`. This doesn't highlight properly:
```
let parseJsonValueArray (str: (string)): 'a =
    str
    asdf
```

But this does:
```
let parseJsonValueArray (str: (string)) : 'a =
    str
    asdf
```

**Comment by MangelMaxime** [comment]
Thank you both :)

**Comment by seanpoulter** [comment]
I never ever thought I'd ever be able to say it, but I think a Bison grammar file is easier to read. 😆 How does one go about testing the parsing? My wild guess is to play around [here](https://github.com/ionide/ionide-fsgrammar/blob/master/grammar/fsharp.json#L429).

**Comment by MangelMaxime** [comment]
@seanpoulter Yes the grammar is kind of complexe to understand. One of the reason is also because I when I first started to work on it I didn't know that we could support "balanced" expression. 

So some part of the grammar feel likes catching edges case, I am refactoring each time a bit more the grammar to remove this "technical debt" but I can't modify everything at once.

In general, when working on the grammar I try to delete some rules and until I find the one controlling the scope I want. And from there, I start adding new rules or fixing the existing ones.

**Comment by seanpoulter** [comment]
Thanks folks! 👌
