### ISSUE TITLE
Similar lines highlighted differently

### ISSUE THREAD

**Issue by LiteracyFanatic** [ionide/ionide-fsgrammar#158]
**Describe the bug**
The following example produces incorrect syntax highlighting.

**To Reproduce**

```fsharp
module Test
let parts = [| 1; 2; 3 |]
let a = parts |> Array.tryItem 0
let b = parts |> Array.tryItem 1
let c = parts |> Array.tryItem 2
```

**Expected behaviour**

**Screenshots**
![2021-01-30T20:16:12-06:00](https://user-images.githubusercontent.com/18249574/106372713-44e35680-6338-11eb-8a74-d76d9723ab0f.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Ionide version: 5.2.0
 - VSCode version: 1.52.1
 - dotnet SDK version: 5.0.102

**Comment by MangelMaxime** [comment]
I cannot reproduce the problem

![image](https://user-images.githubusercontent.com/4760796/163200513-df57768b-0cdb-4985-b905-e36010c76951.png)

And I don't think this problem was coming from the grammar but probably more from the semantic highlight which can takes sometimes to kick in and so don't refresh as fast as you type.

**Comment by MangelMaxime** [comment]
@baronfel While you are around ;) 

I think this issue too can be closed.

**Comment by LiteracyFanatic** [comment]
I can confirm that this example highlights correctly now. Thanks!
