### ISSUE TITLE
Syntax highlighting missing for `let struct`

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-fsgrammar#199]
### Describe the bug

I feel like `let struct (x0, y0)` should be highlighted the same as the line above.

### Link to sample reproduction
```fs
let origin = struct (0,0)
let (struct (x0,y0)) = origin
```

Linked to https://github.com/ionide/ionide-vscode-fsharp/issues/1937

### Screenshots
![CleanShot 2023-09-28 at 20 01 44](https://github.com/ionide/ionide-fsgrammar/assets/4760796/06455d68-0226-474b-8ff9-7ba7df941220)

## Machine info
 - OS: Linux
 - .NET SDK version: [e.g. 5.0.100]
 - Ionide version: 7.12.3

**Comment by jkillingsworth** [comment]
I have a different opinion about this. Since `struct` is a [language keyword](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/keyword-reference), I think it should always be highlighted the same color as other language keywords (i.e. `let`, `type`, `of`, etc.). This is how it works in Visual Studio 2022. See screenshot below.

![shot-1](https://github.com/ionide/ionide-fsgrammar/assets/1977895/79bb5741-309b-4223-9167-e4a0f7fb328d)

The above shows the correct behavior in my opinion. In this example, `One` is a discriminated union case, not a language keyword. A union case is a different classification than a language keyword, therefore it can be a different color. The screenshot below shows the same color scheme in VS Code.

![shot-2](https://github.com/ionide/ionide-fsgrammar/assets/1977895/c2fe4828-1374-4867-b0d8-d73e507f7f08)

I think the `struct` on line 3 should be highlighted in blue the same as it is on line 2. I think everything else in this example is working correctly.

For reference, here are the relevant color settings I am using:

    "editor.semanticTokenColorCustomizations": {
        "rules": {

            // ...

            "enumMember": {
                "foreground": "#c0c000"
            },

            // ...

        }
    },


    "editor.tokenColorCustomizations": {
        "textMateRules": [

            // ...
            
            {
                "scope": [
                    "keyword",
                ],
                "settings": {
                    "foreground": "#569cd6"
                }
            },

            // ...
        ]
    },

**Comment by MangelMaxime** [comment]
You are right indeed, I knew it needed to be colorised but didn't think farther enough :).

It should be colorised as a `keyword` indeed.
